logging:
  level:
    root: info
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: errors
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://mysql-container:3306/prolog?serverTimezone=Asia/Seoul
    username: root
    password: 8344
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: redis-container
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    web:
      pageable:
        one-indexed-parameters: true