logging:
  level:
    root: info
spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: errors
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/prolog?serverTimezone=Asia/Seoul
    username: root
    password: tkd5957!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true